CREATE TABLE "R_RECORD_DEPENDENT" (
	"MASTER_UUID_ID" VARCHAR2 (64) NOT NULL,
	"META_ID" VARCHAR2 (225) NOT NULL,
	"META_TYPE" VARCHAR2 (16) NOT NULL,
	"CREATE_TIME" DATE NOT NULL
);

CREATE TABLE "R_RECORD_HISTORY" (
	"UUID" VARCHAR2 (64) NOT NULL,
	"ID" VARCHAR2 (225) NOT NULL,
	"NAME" VARCHAR2 (64) NOT NULL,
	"ID_RUN" VARCHAR2 (64),
	"STATUS" VARCHAR2 (64) DEFAULT '' NOT NULL,
	"HOSTNAME" VARCHAR2 (64),
	"ERROR_MSG" VARCHAR2 (1024),
	"CREATE_TIME" DATE NOT NULL
);

CREATE TABLE "R_RECORD_JOB" (
	"UUID" VARCHAR2 (64) NOT NULL,
	"ID_JOB" VARCHAR2 (225) NOT NULL,
	"NAME_JOB" VARCHAR2 (64) NOT NULL,
	"ID_RUN" VARCHAR2 (64) NULL,
	"STATUS" VARCHAR2 (64) NOT NULL,
	"HOSTNAME" VARCHAR2 (64) NULL,
	"CRON_EXPRESSION" VARCHAR2 (16) NULL,
	"ERROR_MSG" VARCHAR2 (512) NULL,
	"CREATE_TIME" DATE NOT NULL,
	"UPDATE_TIME" DATE NOT NULL,
	PRIMARY KEY ("ID_JOB", "UUID")
);